services:
  app:
    image: bloglist-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/bloglist?authSource=admin
      - SECRET=devsecret
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bloglist
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - backend

volumes:
  mongo_data:
